### ISSUE TITLE
exception thrown when I try expand an Emmet abbreviation using ctrl-e

### ISSUE THREAD

**Issue by rcrooks** [paradoxxxzero/atom-undo-tree#1]
that's it - exception thrown, prevented the abbreviation from expanding. Had to disable the package for now, as I use Emmet constantly, but hope you'll be able to fix it.

What I did:

1. typed ol.bcls-tasklist>li*5
2. pressed ctrl-e

Error was something like "unable to find beginning of line" or something like that. Will reenable undo-tree and do it again if you need me to.

**Comment by paradoxxxzero** [comment]
This extension is a work in progress because as of now it relies on a dirty hack. I hope to find a cleaner way to implement this (implementing this directly in atom would be easier). 
In the meantime I will try to fix a maximum of bugs.
Thanks for reporting, I'll take a look

**Comment by paradoxxxzero** [comment]
Can you confirm this is fixed in 0.2.0?
Thanks

**Comment by rcrooks** [comment]
Afraid not -- here's the full error message:
Uncaught TypeError: Cannot read property 'start' of undefined
/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:823
Show Stack Trace
The error was thrown from the undo-tree package. You can help by creating an issue. Please explain what actions triggered this error.

**Comment by rcrooks** [comment]
ah, relaunched Atom, and all is well. Thanks!
